definitions:
  WebAPIController.CreateRequest:
    properties:
      Email:
        type: string
      FirstName:
        type: string
      LastName:
        type: string
      Password:
        type: string
      Username:
        type: string
    type: object
info:
  contact: {}
  title: Swagger UserService API
paths:
  /api/v1/users:
    post:
      consumes:
      - application/json
      parameters:
      - description: command
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/WebAPIController.CreateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema: {}
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      tags:
      - Users
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: '"Authorization"'
    type: apiKey
swagger: "2.0"
